name: "build"
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, macos-13]
    runs-on: matrix.os
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v24
    - uses: cachix/cachix-action@v12
      with:
        name: fanshi1028-personal
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - run: nix build
